CREATE TABLE IF NOT EXISTS Simian (
    Id SERIAL PRIMARY KEY,
    Dna VARCHAR (250) NOT NULL,
    IsSimian BOOLEAN NOT NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
